mds1/multicall3

README.md

@mds1 I haven't verified the contract yet on the new Etherscan Sepolia explorer. If you want that this is part of this PR let me know and I will verify it.

Update to Sepolia Etherscan

---

README.md

Fixes a minimal typo in the Readme :P

fix(readme): OCD Typo

---

deployments.json

Testnet was requested here: https://github.com/mds1/multicall/issues/69
Deployed on mainnet a few weeks ago: https://basescan.org/address/0xca11bde05977b3631167028862be2a173976ca11#code

Add Base mainnet

---

deployments.json

Deployment done using the pre-signed transaction:
https://edgscan.live/tx/0x07471adfe8f4ec553c1199f495be97fc8be8e0626ae307281c22534460184ed1
Thanks!

Add Edgeware EdgeEVM mainnet

---

deployments.json

Deploy on opBNB Mainnet, please check: https://mainnet.opbnbscan.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?p=1&tab=Contract

deploy on opBNB Mainnet

---

deployments.json

As title. Contract is verified as well.

➕ Add Base Sepolia Deployment

---

deployments.json

Add Zora Sepolia (Chain id 999999999) to deployments

Add Zora Sepolia Testnet deployment

---

deployments.json

- update `deployments.json`
- add zKatana, a Sepolia zkEVM testnet by Astar network

Add Astar zKatana testnet

---

deployments.json

- Update `deployments.json`
- Add Xai Testnet - chain id: 47279324479

Add Xai Testnet

---

deployments.json

Replaces https://github.com/mds1/multicall/pull/175 since I couldn't push to that branch to resolve the conflicts

chore: add jfin chain to `deployments.json`

---

deployments.json

https://github.com/mds1/multicall/issues/76#issuecomment-1843199492

chore: add zkSync Era Sepolia Testnet

---

deployments.json

Update deployments.json
Add Astar zkEVM Testnet (zKatana) - chain id: 1261120

Add Astar zKatana Testnet deployment

---

deployments.json

* https://palm.chainlens.com/contracts/0xca11bde05977b3631167028862be2a173976ca11/sources
* https://testnet.palm.chainlens.com/contracts/0xca11bde05977b3631167028862be2a173976ca11/sources
Palm network docs: https://docs.palm.io

chore: add Palm network deploys

---

deployments.json

- Update deployments.json
- Add Xai Mainnet - chain id: 660279

Add Xai Mainnet

---

deployments.json

I have deployed multicall contract on Kroma sepolia testnet. 
Please update the deployment.json file regarding the additions.
etherscan : https://sepolia.kromascan.com/address/0xcA11bde05977b3631167028862bE2a173976CA11#code
docs : https://docs.kroma.network/testnet/setup

chore: update deployments.json about Kroma sepolia testnet

---

deployments.json

1. Update core hub network info on testnet (Calypso, Europa, Nebula, Titan)
2. Remove Chaos + Psyche Staging v3 Chains
3. Update Calypso Name to Calypso Hub
4. Update Titan Name to AI Hub

Update Deployments for SKALE Network

---

deployments.json

👋 
Adds both Immutable zkEVM Mainnet and Immutable zkEVM Testnet to `deployments.json`

Add Immutable zkEVM to deployments.json

---

deployments.json

**Pull Request Summary**
- Removed zKatana (testnet being discontinued)
- Fixed url for Astar zkEVM
- Added address for zKyoto testnet

Add zKyoto

---

deployments.json

You've already deployed it 👍 . This PR only modifies `deployments.json`.

Add Polygon Amoy

---

deployments.json

Add deployments json for Xterio Chain mainnet and testnet

add deployments for Xterio Chain

---

deployments.json

Deployment on Etherlink mainnet, and update explorer link for Etherlink testnet

feat: Etherlink deployment

---

deployments.json

Deployment on Overprotocol mainnet, testnet

Add over protocol mainnet, testnet deploy

---

deployments.json

add Superseed

---

deployments.json

Add Flow Mainnet/Testnet to deployments.json

---

deployments.json

Sonic is deployed already, we need to update it: https://sonicscan.org/address/0xca11bde05977b3631167028862be2a173976ca11

feat: add sonic deployments

---

deployments.json

deployed at peaq network - https://peaq.subscan.io/account/0xca11bde05977b3631167028862be2a173976ca11?tab=contract&evm_contract_tab=code

Add peaq network

---

deployments.json

I deployed and verified the Multicall3 contract on Morph mainnet, https://explorer.morphl2.io/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract, In this PR I added it to the list.

Added Morph Mainnet 

---

deployments.json

https://github.com/mds1/multicall/issues/313#issuecomment-2616951783

chore: add Abstract Mainnet

---

deployments.json

[Core Testnet2](https://coredao.org/explore/blog/core-testnet2-with-bitcoin-testnet4-integration-goes-live)

chore: add Core Testnet2 deploy

---

deployments.json

I deployed and verified the Multicall3 contract on Morph holesky, https://explorer-holesky.morphl2.io/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract, In this PR I added it to the list.

Added Morph Holesky

---

deployments.json

Add Monad Testnet

---

deployments.json

Hey there!
I have added Whitechain deployment to `deployments.json`. 
Please, have a look.
Thanks!

Update deployments.json with new deployment on Whitechain

---

deployments.json

Addresses are listed in their official docs [here](https://docs.inkonchain.com/useful-information/contracts#ink-mainnet-1).

Add Ink and Ink Sepolia addresses
